---
title: "Miniproyecto"
author: "juan antonio zarceño goznalez, Carla Giménez Piqueres"
date: "2026-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1.Introducción.
  
```{r}
library(readr)
datos <- read_delim("data/65334.csv", 
                    delim = ";", 
                    escape_double = FALSE, 
                    trim_ws = TRUE)
#LIMPIEZA DE LOS DATOS, PARA QUE QUEDEN BIEN
datos$Total <- as.numeric(gsub(",", ".", datos$Total))
datos_limpios <- subset(
  datos,
  Sexo != "Ambos sexos" &
  Edad != "Total" &
  `Comunidades y Ciudades Autónomas` != "Total Nacional"
)

datos_limpios <- na.omit(datos_limpios)
```

##Preguntas de investigación

1) ¿Qué comunidad autónoma tiene la tasa de paro más alta actualmente? 

2) ¿Existe una brecha real entre el paro masculino y femenino en los jóvenes? 

3) ¿Cómo afecta la edad a la probabilidad de estar en paro? 

##Visualizaciones

1) Figura 1: Tasa de Paro por CCAA y Sexo
```{r}
library(ggplot2)

ggplot(data = datos_limpios, 
       mapping = aes(x = reorder(`Comunidades y Ciudades Autónomas`, Total), y = Total, fill = Sexo)) + geom_bar(stat = "identity", position = "dodge") + coord_flip() +
labs(title = "Tasa de Paro por CCAA y Sexo", x = "Comunidad Autónoma", y = "Tasa de Paro (%)", fill = "Sexo") + theme_minimal()
```

